import { useMemo } from "react";

function useName(){

    const randomNames = useMemo(() => [
        "Gafitas",
        "Woody Woodpecker",
        "Sir Jamie",
        "Jon Voight",
        "James Woods",
        "Kid Rock",
        "Tim Allen",
        "Patricia Heaton",
        "Scott Baio", 
        "Adam Carolla",
        "Ted Nugent", 
        "Mitch McConnell",
        "Kelsey Grammer",
        "Clint Eastwood",
        "Ron DeSantis",
        "Marjorie Taylor Greene",
        "Josh Hawley", 
        "Lauren Boebert",
        "Rand Paul",
        "Elise Stefanik",
        "Kristi Noem", 
        "Humphrey Bogart",
        "Cary Grant",
        "James Stewart",
        "John Wayne",
        "Gregory Peck",
        "Charlton Heston",
        "Spencer Tracy",
        "Clark Gable",
        "Burt Lancaster",
        "Kirk Douglas",
        "Mick Jagger",
        "Freddie Mercury",
        "Jimi Hendrix",
        "Kurt Cobain",
        "David Bowie",
        "Eddie Van Halen", 
        "Axl Rose",
        "Steven Tyler",
        "Paul McCartney",
        "Ozzy Osbourne",
        "Neil Tyson",
        "Richard Dawkins",
        "Stephen Hawking",
        "Noam Chomsky",
        "Jane Goodall",
        "Michio Kaku",
        "Carl Sagan",
        "Brian Greene",
        "Lisa Randall",
        "Yuval Noah Harari",
        "Bobert McSnazzle",
        "Chester von Picklewig",
        "Tuna McFlapjack",
        "Zorpington Fizzwhistle",
        "Wally O’Shenanigans",
        "Dr. Chonkers McGirth",
        "Spanky Wobblebottom",
        "Noodleton Q. Wafflesnack",
        "Sir Borkington Woofster",
        "Bloop McDoodle",
        "Snargle Von Wagglesnarf",
        "Pudding T. Butterbiscuit",
        "Bartholomew Jigglenuts",
        "Picklesworth Bumblefluff",
        "Viktor Tsoy",
        "Boingo McSproingus",
        "Twinkie von Squeegee",
        "Tater Totterson",
        "Buster Snagglepants",
        "Doodleberry Flapjackson",
        "Ziggy Boondoggle",
        "Crusty McNoodle",
        "Dingo Fizzlebottom",
        "Imogen",
        "Wubba G. Muffinsnarf",
        "Janky Sporkletoes",
        "Soggy McMuffin",
        "Plonkus D. Fiddlewhack",
        "Oinky von Snortsniff",
        "Gorgonzola McSprinkle",
        "Doinkus M. Fizzsnort",
        "Snickers Bloopington",
        "Oleg Zimin",
        "Egor Letov",
        "Boomer Snaggleflap",
        "Floof McDander",
        "Frito Baggins",
        "Wilhelm Richard Wagner",
        "Noelia Sánchez",
        "gioacchino rossini",
        "Lumpy Squiggletoes",
        "Nubbins O’Doodle",
        "Wibby von Wobblestein",
        "Thadwick Pumpernickel",
        "Seva",
        "Abel",
        "Quibble McWiggles",
        "Sploofington Snortley",
        "Blorbo von Zonk",
        "Pilar Torres",
        "Squeaky Doodlefizz",
        "Lorpington M. Fizzleflop",
        "Dorkus B. Jibberwomp",
        "Pickleberry Snootsnarf",
        "Zamboni McSlurp",
        "Wampus Q. Squizzlewomp",
        "Snorgle Muffinwhack",
        "Quasimodo McJiggle",
        "Chonkleberry Wobbleboots",
        "Bloopington Fuzzlewump",
        "Stefan",
        "Andrew"
    ], []);
    
    function getRandomName(){
        const index = Math.trunc(Math.random() * randomNames.length);
        return randomNames[index];
    }
    
    return { getRandomName }
}

export { useName }